# -*- encoding: utf-8 -*-

=begin
#MoneyKit API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2023-02-18

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.1.0

=end

$:.push File.expand_path("../lib", __FILE__)
require "moneykit/version"

Gem::Specification.new do |s|
  s.name        = "moneykit"
  s.version     = MoneyKit::VERSION
  s.platform    = Gem::Platform::RUBY
  s.authors     = ["MoneyKit"]
  s.email       = [""]
  s.homepage    = "https://github.com/moneykit/moneykit-ruby-sdk"
  s.summary     = "MoneyKit API Ruby Gem"
  s.description = "MoneyKit API"
  s.license     = "Unlicense"
  s.required_ruby_version = ">= 2.7"
  s.metadata = {}

  s.add_runtime_dependency 'faraday', '>= 1.0.1', '< 3.0'
  s.add_runtime_dependency 'faraday-multipart'

  s.add_development_dependency 'rspec', '~> 3.6', '>= 3.6.0'

  s.files         = `find *`.split("\n").uniq.sort.select { |f| !f.empty? }
  s.test_files    = `find spec/*`.split("\n")
  s.executables   = []
  s.require_paths = ["lib"]
end
