=begin
#MoneyKit API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2023-02-18

Generated by: https://openapi-generator.tech
Generator version: 7.12.0

=end

require 'spec_helper'
require 'json'

# Unit tests for MoneyKit::AccountsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'AccountsApi' do
  before do
    # run before each test
    @api_instance = MoneyKit::AccountsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AccountsApi' do
    it 'should create an instance of AccountsApi' do
      expect(@api_instance).to be_instance_of(MoneyKit::AccountsApi)
    end
  end

  # unit tests for get_account
  # /links/{id}/accounts/{account_id}
  # Fetches a single account associated with a &lt;a href&#x3D;#tag/Links&gt;link&lt;/a&gt;.
  # @param id The unique ID for this link.
  # @param account_id The account ID to fetch.
  # @param [Hash] opts the optional parameters
  # @return [GetAccountResponse]
  describe 'get_account test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_account_numbers
  # /links/{id}/accounts/numbers
  # Returns a list of open, permissioned accounts associated with a &lt;a href&#x3D;#tag/Links&gt;link&lt;/a&gt;,         including full account and routing numbers for appropriate accounts (such as checking and savings accounts).         &lt;p&gt;**Note** that this endpoint does **not** trigger a fetch of account numbers from the institution; it merely returns         account numbers that have already been fetched, either because &#x60;prefetch&#x60; was requested when the link was created,         or because of an on-demand update.  **To force a check for new/updated account numbers, you must use the         &lt;a href&#x3D;#operation/refresh_products&gt;/products&lt;/a&gt; endpoint.**         &lt;p&gt;If you have requested prefetch or an on-demand update, you should check the &#x60;refreshed_at&#x60; date     for this product in the returned response, and compare that against the previous &#x60;refreshed_at&#x60; date, which you can     get from any previous response for this or any other account or link request.  If the refreshed_at date has not     increased, then updated data is not yet available.
  # @param id The unique ID for this link.
  # @param [Hash] opts the optional parameters
  # @return [GetAccountNumbersResponseLegacy20230218]
  describe 'get_account_numbers test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_accounts
  # /links/{id}/accounts
  # Returns a list of open, permissioned accounts associated with a &lt;a href&#x3D;#tag/Links&gt;link&lt;/a&gt;.
  # @param id The unique ID for this link.
  # @param [Hash] opts the optional parameters
  # @option opts [Array<String>] :account_ids An optional list of account IDs to filter the results.
  # @return [GetAccountsResponse]
  describe 'get_accounts test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_user_accounts
  # /users/{id}/accounts
  # Fetches all accounts belonging to a &lt;a href&#x3D;#operation/get_user_accounts&gt;user&lt;/a&gt;.
  # @param id The unique ID for this user.  This is the same ID provided         in the call to &lt;a href&#x3D;/api/operation/create_link_session#customer_user-id&gt;link-session&lt;/a&gt; to create any link for this user.
  # @param [Hash] opts the optional parameters
  # @option opts [Array<String>] :account_ids If present, filters results to accounts matching the given IDs.
  # @option opts [Array<String>] :institution_ids DEPRECATED; ignored
  # @return [GetUserAccountsResponse]
  describe 'get_user_accounts test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
