=begin
#MoneyKit API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2023-02-18

Generated by: https://openapi-generator.tech
Generator version: 7.12.0

=end

require 'spec_helper'
require 'json'

# Unit tests for MoneyKit::IdentityApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'IdentityApi' do
  before do
    # run before each test
    @api_instance = MoneyKit::IdentityApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of IdentityApi' do
    it 'should create an instance of IdentityApi' do
      expect(@api_instance).to be_instance_of(MoneyKit::IdentityApi)
    end
  end

  # unit tests for get_identities
  # /links/{id}/identity
  # Returns account owner information from the institution, including names, emails, phone     numbers, and addresses, for all permissioned accounts associated with a &lt;a href&#x3D;#tag/Links&gt;link&lt;/a&gt;.  This information     will appear in the &#x60;owners&#x60; list in the &#x60;accounts&#x60; object.     &lt;p&gt;Some fields may be empty, if not provided by the institution.     &lt;p&gt;**Note** that this endpoint does **not** trigger a fetch of owner information from the institution; it merely returns     owner information that has already been fetched, either because &#x60;prefetch&#x60; was requested when the link was created,     or because of an on-demand update.  **To force a check for new/updated owner information, you must use the     &lt;a href&#x3D;#operation/refresh_products&gt;/products&lt;/a&gt; endpoint.**     &lt;p&gt;If you have requested prefetch or an on-demand update, you should check the &#x60;refreshed_at&#x60; date     for this product in the returned response, and compare that against the previous &#x60;refreshed_at&#x60; date, which you can     get from any previous response for this or any other account or link request.  If the refreshed_at date has not     increased, then updated data is not yet available.
  # @param id The unique ID for this link.
  # @param [Hash] opts the optional parameters
  # @option opts [Array<String>] :account_ids An optional list of account IDs to filter the results.
  # @return [IdentityResponse]
  describe 'get_identities test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
