=begin
#MoneyKit API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2023-02-18

Generated by: https://openapi-generator.tech
Generator version: 7.12.0

=end

require 'spec_helper'
require 'json'

# Unit tests for MoneyKit::InstitutionsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'InstitutionsApi' do
  before do
    # run before each test
    @api_instance = MoneyKit::InstitutionsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of InstitutionsApi' do
    it 'should create an instance of InstitutionsApi' do
      expect(@api_instance).to be_instance_of(MoneyKit::InstitutionsApi)
    end
  end

  # unit tests for get_institution
  # /institutions/{institution_id}
  # Fetches details about a single institution.
  # @param institution_id The institution ID to fetch.
  # @param [Hash] opts the optional parameters
  # @return [Institution]
  describe 'get_institution test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_institutions
  # /institutions
  # Fetches a list of institutions, optionally filtered by name.  Results are paginated.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :name If provided, returns only institutions containing this name (wholly or as a prefix).
  # @option opts [Boolean] :featured If true, returns only featured institutions.
  # @option opts [String] :cursor Cursor to fetch the next set of institutions. (You get this value from the previous call to &#x60;/institutions&#x60;.)
  # @option opts [Integer] :limit A limit on the number of institutions to be returned.
  # @return [GetInstitutionsResponse]
  describe 'get_institutions test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
