=begin
#MoneyKit API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2023-02-18

Generated by: https://openapi-generator.tech
Generator version: 7.12.0

=end

require 'spec_helper'
require 'json'

# Unit tests for MoneyKit::InvestmentsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'InvestmentsApi' do
  before do
    # run before each test
    @api_instance = MoneyKit::InvestmentsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of InvestmentsApi' do
    it 'should create an instance of InvestmentsApi' do
      expect(@api_instance).to be_instance_of(MoneyKit::InvestmentsApi)
    end
  end

  # unit tests for get_holdings
  # /links/{id}/investments/holdings
  # Returns holdings for the investment accounts associated with a &lt;a href&#x3D;#tag/Links&gt;link&lt;/a&gt;.     &lt;p&gt;**Note** that this endpoint does **not** trigger a fetch of holdings from the institution; it merely returns     holdings that have already been fetched.  **To force a check for new/updated owner information, you must use the     &lt;a href&#x3D;#operation/refresh_products&gt;/products&lt;/a&gt; endpoint.**     &lt;p&gt;If you have requested prefetch or an on-demand update, you should check the &#x60;refreshed_at&#x60; date     for this product in the returned response, and compare that against the previous &#x60;refreshed_at&#x60; date, which you can     get from any previous response for this or any other account or link request.  If the refreshed_at date has not     increased, then updated data is not yet available.
  # @param id The unique ID for this link.
  # @param [Hash] opts the optional parameters
  # @option opts [Array<String>] :account_ids An optional list of account IDs to filter the results.
  # @return [GetHoldingsResponse]
  describe 'get_holdings test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_investment_transactions
  # /links/{id}/investments/transactions
  # Returns investment transactions for the accounts associated with a &lt;a href&#x3D;#tag/Links&gt;link&lt;/a&gt;.     Results are paginated, and returned in reverse chronological order.     &lt;p&gt;**Note** that this endpoint does **not** trigger a fetch of transactions from the institution; it merely returns     transactions that have already been fetched.  **To force a check for new/updated owner information, you must use the     &lt;a href&#x3D;#operation/refresh_products&gt;/products&lt;/a&gt; endpoint.**     &lt;p&gt;If you have requested prefetch or an on-demand update, you should check the &#x60;refreshed_at&#x60; date     for this product in the returned response, and compare that against the previous &#x60;refreshed_at&#x60; date, which you can     get from any previous response for this or any other account or link request.  If the refreshed_at date has not     increased, then updated data is not yet available.
  # @param id The unique ID for this link.
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page The page number to return.
  # @option opts [Integer] :size The number of items to return per page.
  # @option opts [Array<String>] :account_ids An optional list of account IDs to filter the results.
  # @option opts [Date] :start_date The earliest date for which data should be returned, formatted as YYYY-MM-DD.
  # @option opts [Date] :end_date The latest date for which data should be returned, formatted as YYYY-MM-DD.
  # @return [GetInvestmentTransactionsResponse]
  describe 'get_investment_transactions test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
