=begin
#MoneyKit API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.1.0

=end

require 'spec_helper'
require 'json'

# Unit tests for MoneyKit::LinksApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'LinksApi' do
  before do
    # run before each test
    @api_instance = MoneyKit::LinksApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of LinksApi' do
    it 'should create an instance of LinksApi' do
      expect(@api_instance).to be_instance_of(MoneyKit::LinksApi)
    end
  end

  # unit tests for disconnect
  # /links/{id}
  # Deletes this link and disables its access token.         &lt;p&gt;After deletion, the link id and access token are no longer valid and cannot be used to access any data         that was associated with it.
  # @param id The unique ID for this link.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :moneykit_version 
  # @return [nil]
  describe 'disconnect test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_link
  # /links/{id}
  # Fetches details about a link.
  # @param id The unique ID for this link.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :moneykit_version 
  # @return [LinkResponse]
  describe 'get_link test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_user_links
  # /users/{id}/links
  # Fetches all links belonging to a &lt;a href&#x3D;#operation/get_user_accounts&gt;user&lt;/a&gt;.
  # @param id The unique ID for this user.  This is the same ID provided         in the call to &lt;a href&#x3D;#operation/create_link_session&gt;/link-session&lt;/a&gt; to create any link for this user.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :moneykit_version 
  # @return [GetUserLinksResponse]
  describe 'get_user_links test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for reset_login
  # Force a \&quot;relink required\&quot; state on a link (Test only).
  # @param id The unique ID for this link.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :moneykit_version 
  # @return [LinkResponse]
  describe 'reset_login test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_link
  # /links/{id}
  # Updates the link configuration.
  # @param id The unique ID for this link.
  # @param update_link_request 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :moneykit_version 
  # @return [LinkResponse]
  describe 'update_link test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
