=begin
#MoneyKit API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.1.0

=end

require 'spec_helper'
require 'json'

# Unit tests for MoneyKit::LinkSessionApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'LinkSessionApi' do
  before do
    # run before each test
    @api_instance = MoneyKit::LinkSessionApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of LinkSessionApi' do
    it 'should create an instance of LinkSessionApi' do
      expect(@api_instance).to be_instance_of(MoneyKit::LinkSessionApi)
    end
  end

  # unit tests for create_link_session
  # /link-session
  # This endpoint is to be called by your back end, to establish a new link session         for creating a link to your end user&#39;s institution.
  # @param create_link_session_request 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :moneykit_version 
  # @return [CreateLinkSessionResponse]
  describe 'create_link_session test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for exchange_token
  # /link-session/exchange-token
  # After the end user has successfully completed the linking process, your back end     calls this endpoint to exchange the token received by your front end for a&#x60;link_id&#x60; that can be used to access     the link&#39;s data.
  # @param exchange_token_request 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :moneykit_version 
  # @return [ExchangeTokenResponse]
  describe 'exchange_token test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
