=begin
#MoneyKit API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2023-02-18

Generated by: https://openapi-generator.tech
Generator version: 7.12.0

=end

require 'spec_helper'
require 'json'

# Unit tests for MoneyKit::WebhooksApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'WebhooksApi' do
  before do
    # run before each test
    @api_instance = MoneyKit::WebhooksApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of WebhooksApi' do
    it 'should create an instance of WebhooksApi' do
      expect(@api_instance).to be_instance_of(MoneyKit::WebhooksApi)
    end
  end

  # unit tests for trigger_test_link_webhook_event
  # /webhooks/test/link/{id}
  # Triggers a webhook event for a link, for testing purposes; works only for sandbox links.
  # @param id The unique ID for this link.
  # @param webhook_test_link_request 
  # @param [Hash] opts the optional parameters
  # @return [WebhookTestLinkResponse]
  describe 'trigger_test_link_webhook_event test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
