=begin
#MoneyKit API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.5.0

=end

require 'date'
require 'time'

module MoneyKit
  class LinkError
    SYSTEM_ERROR = "system_error".freeze
    PROVIDER_ERROR = "provider_error".freeze
    INSTITUTION_ERROR = "institution_error".freeze
    USER_ERROR = "user_error".freeze
    AUTH_EXPIRED = "auth_expired".freeze
    INCOMPLETE = "incomplete".freeze
    PAYMENT_ERROR = "payment_error".freeze

    def self.all_vars
      @all_vars ||= [SYSTEM_ERROR, PROVIDER_ERROR, INSTITUTION_ERROR, USER_ERROR, AUTH_EXPIRED, INCOMPLETE, PAYMENT_ERROR].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if LinkError.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #LinkError"
    end
  end
end
