=begin
#MoneyKit API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2023-02-18

Generated by: https://openapi-generator.tech
Generator version: 7.12.0

=end

require 'date'
require 'time'

module MoneyKit
  class MoneyKitConnectFeatures
    # If enabled, the user can report linking issues directly to MoneyKit via 'Report Issue' button.
    attr_accessor :issue_reporter

    # If enabled, the user can register for, or login into, Money ID.
    attr_accessor :enable_money_id

    # If enabled, the user will see a warning when trying to connect to an institution for which             they already have a connected link.
    attr_accessor :duplicate_institution_warning

    # If enabled, all institutions for which the user has a connected link will be hidden, so the user             will be unable to make another link to an institution to which they are already linked.
    attr_accessor :duplicate_institution_rejected

    # If enabled, the user can click a button in the MoneyKit Connect SDK to connect manually if the institution they are looking for doesn't exist in our catalog.
    attr_accessor :connect_manually

    # If enabled, the user is allowed to grant permission only for one account.
    attr_accessor :permit_only_one_account

    # If enabled, the user is allowed to grant permission only for depository accounts.             If there are no depository accounts, the linking process will fail.
    attr_accessor :permit_only_depository_accounts

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'issue_reporter' => :'issue_reporter',
        :'enable_money_id' => :'enable_money_id',
        :'duplicate_institution_warning' => :'duplicate_institution_warning',
        :'duplicate_institution_rejected' => :'duplicate_institution_rejected',
        :'connect_manually' => :'connect_manually',
        :'permit_only_one_account' => :'permit_only_one_account',
        :'permit_only_depository_accounts' => :'permit_only_depository_accounts'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'issue_reporter' => :'Boolean',
        :'enable_money_id' => :'Boolean',
        :'duplicate_institution_warning' => :'Boolean',
        :'duplicate_institution_rejected' => :'Boolean',
        :'connect_manually' => :'Boolean',
        :'permit_only_one_account' => :'Boolean',
        :'permit_only_depository_accounts' => :'Boolean'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `MoneyKit::MoneyKitConnectFeatures` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `MoneyKit::MoneyKitConnectFeatures`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'issue_reporter')
        self.issue_reporter = attributes[:'issue_reporter']
      else
        self.issue_reporter = false
      end

      if attributes.key?(:'enable_money_id')
        self.enable_money_id = attributes[:'enable_money_id']
      else
        self.enable_money_id = false
      end

      if attributes.key?(:'duplicate_institution_warning')
        self.duplicate_institution_warning = attributes[:'duplicate_institution_warning']
      else
        self.duplicate_institution_warning = false
      end

      if attributes.key?(:'duplicate_institution_rejected')
        self.duplicate_institution_rejected = attributes[:'duplicate_institution_rejected']
      else
        self.duplicate_institution_rejected = false
      end

      if attributes.key?(:'connect_manually')
        self.connect_manually = attributes[:'connect_manually']
      else
        self.connect_manually = false
      end

      if attributes.key?(:'permit_only_one_account')
        self.permit_only_one_account = attributes[:'permit_only_one_account']
      else
        self.permit_only_one_account = false
      end

      if attributes.key?(:'permit_only_depository_accounts')
        self.permit_only_depository_accounts = attributes[:'permit_only_depository_accounts']
      else
        self.permit_only_depository_accounts = false
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          issue_reporter == o.issue_reporter &&
          enable_money_id == o.enable_money_id &&
          duplicate_institution_warning == o.duplicate_institution_warning &&
          duplicate_institution_rejected == o.duplicate_institution_rejected &&
          connect_manually == o.connect_manually &&
          permit_only_one_account == o.permit_only_one_account &&
          permit_only_depository_accounts == o.permit_only_depository_accounts
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [issue_reporter, enable_money_id, duplicate_institution_warning, duplicate_institution_rejected, connect_manually, permit_only_one_account, permit_only_depository_accounts].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        ::Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = MoneyKit.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end
  end
end
