=begin
#MoneyKit API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2023-02-18

Generated by: https://openapi-generator.tech
Generator version: 7.12.0

=end

require 'date'
require 'time'

module MoneyKit
  class Product
    ACCOUNTS = "accounts".freeze
    ACCOUNT_NUMBERS = "account_numbers".freeze
    IDENTITY = "identity".freeze
    TRANSACTIONS = "transactions".freeze
    INVESTMENTS = "investments".freeze
    ENRICHMENT = "enrichment".freeze

    def self.all_vars
      @all_vars ||= [ACCOUNTS, ACCOUNT_NUMBERS, IDENTITY, TRANSACTIONS, INVESTMENTS, ENRICHMENT].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if Product.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #Product"
    end
  end
end
