=begin
#MoneyKit API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2023-02-18

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.1.0

=end

require 'date'
require 'time'

module MoneyKit
  class PublicLinkError
    SYSTEM_ERROR = "system_error".freeze
    PROVIDER_ERROR = "provider_error".freeze
    INSTITUTION_ERROR = "institution_error".freeze
    USER_ERROR = "user_error".freeze
    AUTH_EXPIRED = "auth_expired".freeze
    INCOMPLETE = "incomplete".freeze
    NO_ACCOUNTS = "no_accounts".freeze
    USER_SETUP_REQUIRED = "user_setup_required".freeze
    INVALID_CREDENTIALS = "invalid_credentials".freeze
    USER_OAUTH_DENIED = "user_oauth_denied".freeze
    USER_INPUT_INCORRECT = "user_input_incorrect".freeze

    def self.all_vars
      @all_vars ||= [SYSTEM_ERROR, PROVIDER_ERROR, INSTITUTION_ERROR, USER_ERROR, AUTH_EXPIRED, INCOMPLETE, NO_ACCOUNTS, USER_SETUP_REQUIRED, INVALID_CREDENTIALS, USER_OAUTH_DENIED, USER_INPUT_INCORRECT].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if PublicLinkError.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #PublicLinkError"
    end
  end
end
