=begin
#MoneyKit API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2023-02-18

Generated by: https://openapi-generator.tech
Generator version: 7.12.0

=end

require 'date'
require 'time'

module MoneyKit
  class PublicLinkState
    CONNECTING = "connecting".freeze
    AWAITING_TOKEN_EXCHANGE = "awaiting_token_exchange".freeze
    CONNECTED = "connected".freeze
    DELETED = "deleted".freeze
    ERROR = "error".freeze

    def self.all_vars
      @all_vars ||= [CONNECTING, AWAITING_TOKEN_EXCHANGE, CONNECTED, DELETED, ERROR].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if PublicLinkState.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #PublicLinkState"
    end
  end
end
