=begin
#MoneyKit API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.1.0

=end

require 'date'
require 'time'

module MoneyKit
  class WebhookLinkTestEvent
    LINK_STATE_CHANGED = "link.state_changed".freeze
    LINK_PRODUCT_REFRESH = "link.product_refresh".freeze
    TRANSACTIONS_UPDATES_AVAILABLE = "transactions.updates_available".freeze

    def self.all_vars
      @all_vars ||= [LINK_STATE_CHANGED, LINK_PRODUCT_REFRESH, TRANSACTIONS_UPDATES_AVAILABLE].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if WebhookLinkTestEvent.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #WebhookLinkTestEvent"
    end
  end
end
