=begin
#MoneyKit API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2023-02-18

Generated by: https://openapi-generator.tech
Generator version: 7.12.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for MoneyKit::BudSubcategory
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe MoneyKit::BudSubcategory do
  let(:instance) { MoneyKit::BudSubcategory.new }

  describe 'test an instance of BudSubcategory' do
    it 'should create an instance of BudSubcategory' do
      # uncomment below to test the instance creation
      # expect(instance).to be_instance_of(MoneyKit::BudSubcategory)
    end
  end

end
