=begin
#MoneyKit API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.1.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for MoneyKit::CreateLinkSessionResponse
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe MoneyKit::CreateLinkSessionResponse do
  let(:instance) { MoneyKit::CreateLinkSessionResponse.new }

  describe 'test an instance of CreateLinkSessionResponse' do
    it 'should create an instance of CreateLinkSessionResponse' do
      # uncomment below to test the instance creation
      # expect(instance).to be_instance_of(MoneyKit::CreateLinkSessionResponse)
    end
  end

  describe 'test attribute "link_session_token"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
