=begin
#MoneyKit API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.1.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for MoneyKit::InvestmentsProductSettings
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe MoneyKit::InvestmentsProductSettings do
  let(:instance) { MoneyKit::InvestmentsProductSettings.new }

  describe 'test an instance of InvestmentsProductSettings' do
    it 'should create an instance of InvestmentsProductSettings' do
      # uncomment below to test the instance creation
      # expect(instance).to be_instance_of(MoneyKit::InvestmentsProductSettings)
    end
  end

  describe 'test attribute "required"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "prefetch"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "product"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
