=begin
#MoneyKit API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2023-02-18

Generated by: https://openapi-generator.tech
Generator version: 7.12.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for MoneyKit::LinkProductState
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe MoneyKit::LinkProductState do
  let(:instance) { MoneyKit::LinkProductState.new }

  describe 'test an instance of LinkProductState' do
    it 'should create an instance of LinkProductState' do
      # uncomment below to test the instance creation
      # expect(instance).to be_instance_of(MoneyKit::LinkProductState)
    end
  end

end
