=begin
#MoneyKit API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.1.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for MoneyKit::Provider
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe MoneyKit::Provider do
  let(:instance) { MoneyKit::Provider.new }

  describe 'test an instance of Provider' do
    it 'should create an instance of Provider' do
      # uncomment below to test the instance creation
      # expect(instance).to be_instance_of(MoneyKit::Provider)
    end
  end

end
