=begin
#MoneyKit API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2023-02-18

Generated by: https://openapi-generator.tech
Generator version: 7.12.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for MoneyKit::TransactionRecurrenceResponse
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe MoneyKit::TransactionRecurrenceResponse do
  let(:instance) { MoneyKit::TransactionRecurrenceResponse.new }

  describe 'test an instance of TransactionRecurrenceResponse' do
    it 'should create an instance of TransactionRecurrenceResponse' do
      # uncomment below to test the instance creation
      # expect(instance).to be_instance_of(MoneyKit::TransactionRecurrenceResponse)
    end
  end

  describe 'test attribute "frequency"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "next_predicted_date"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
