=begin
#Plaid Compatibility Layer

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.1.1

=end

# Common files
require 'plaid_compatible/money_kit_plaid_compatible/api_client'
require 'plaid_compatible/money_kit_plaid_compatible/api_error'
require 'plaid_compatible/money_kit_plaid_compatible/version'
require 'plaid_compatible/money_kit_plaid_compatible/configuration'

# Models
require 'plaid_compatible/money_kit_plaid_compatible/models/account_balance'
require 'plaid_compatible/money_kit_plaid_compatible/models/account_base'
require 'plaid_compatible/money_kit_plaid_compatible/models/account_identity'
require 'plaid_compatible/money_kit_plaid_compatible/models/account_subtype'
require 'plaid_compatible/money_kit_plaid_compatible/models/account_type'
require 'plaid_compatible/money_kit_plaid_compatible/models/accounts_get_request'
require 'plaid_compatible/money_kit_plaid_compatible/models/accounts_get_request_options'
require 'plaid_compatible/money_kit_plaid_compatible/models/accounts_get_response'
require 'plaid_compatible/money_kit_plaid_compatible/models/address'
require 'plaid_compatible/money_kit_plaid_compatible/models/address_data'
require 'plaid_compatible/money_kit_plaid_compatible/models/auth_get_numbers'
require 'plaid_compatible/money_kit_plaid_compatible/models/auth_get_request'
require 'plaid_compatible/money_kit_plaid_compatible/models/auth_get_request_options'
require 'plaid_compatible/money_kit_plaid_compatible/models/auth_get_response'
require 'plaid_compatible/money_kit_plaid_compatible/models/country_code'
require 'plaid_compatible/money_kit_plaid_compatible/models/email'
require 'plaid_compatible/money_kit_plaid_compatible/models/http_validation_error'
require 'plaid_compatible/money_kit_plaid_compatible/models/identity_get_request'
require 'plaid_compatible/money_kit_plaid_compatible/models/identity_get_request_options'
require 'plaid_compatible/money_kit_plaid_compatible/models/identity_get_response'
require 'plaid_compatible/money_kit_plaid_compatible/models/institution'
require 'plaid_compatible/money_kit_plaid_compatible/models/institutions_get_by_id_request'
require 'plaid_compatible/money_kit_plaid_compatible/models/institutions_get_by_id_response'
require 'plaid_compatible/money_kit_plaid_compatible/models/item'
require 'plaid_compatible/money_kit_plaid_compatible/models/item_error_webhook'
require 'plaid_compatible/money_kit_plaid_compatible/models/item_get_request'
require 'plaid_compatible/money_kit_plaid_compatible/models/item_get_response'
require 'plaid_compatible/money_kit_plaid_compatible/models/item_public_token_exchange_request'
require 'plaid_compatible/money_kit_plaid_compatible/models/item_public_token_exchange_response'
require 'plaid_compatible/money_kit_plaid_compatible/models/item_remove_request'
require 'plaid_compatible/money_kit_plaid_compatible/models/item_remove_response'
require 'plaid_compatible/money_kit_plaid_compatible/models/item_status_investments'
require 'plaid_compatible/money_kit_plaid_compatible/models/item_status_last_webhook'
require 'plaid_compatible/money_kit_plaid_compatible/models/item_status_nullable'
require 'plaid_compatible/money_kit_plaid_compatible/models/item_status_transactions'
require 'plaid_compatible/money_kit_plaid_compatible/models/link_token_create_request'
require 'plaid_compatible/money_kit_plaid_compatible/models/link_token_create_request_user'
require 'plaid_compatible/money_kit_plaid_compatible/models/link_token_create_response'
require 'plaid_compatible/money_kit_plaid_compatible/models/numbers_ach'
require 'plaid_compatible/money_kit_plaid_compatible/models/numbers_bacs'
require 'plaid_compatible/money_kit_plaid_compatible/models/numbers_eft'
require 'plaid_compatible/money_kit_plaid_compatible/models/numbers_international'
require 'plaid_compatible/money_kit_plaid_compatible/models/owner'
require 'plaid_compatible/money_kit_plaid_compatible/models/personal_finance_category'
require 'plaid_compatible/money_kit_plaid_compatible/models/phone_number'
require 'plaid_compatible/money_kit_plaid_compatible/models/plaid_error'
require 'plaid_compatible/money_kit_plaid_compatible/models/plaid_error_type'
require 'plaid_compatible/money_kit_plaid_compatible/models/products'
require 'plaid_compatible/money_kit_plaid_compatible/models/removed_transaction'
require 'plaid_compatible/money_kit_plaid_compatible/models/transaction'
require 'plaid_compatible/money_kit_plaid_compatible/models/transactions_get_request'
require 'plaid_compatible/money_kit_plaid_compatible/models/transactions_get_request_options'
require 'plaid_compatible/money_kit_plaid_compatible/models/transactions_get_response'
require 'plaid_compatible/money_kit_plaid_compatible/models/transactions_refresh_request'
require 'plaid_compatible/money_kit_plaid_compatible/models/transactions_refresh_response'
require 'plaid_compatible/money_kit_plaid_compatible/models/transactions_sync_request'
require 'plaid_compatible/money_kit_plaid_compatible/models/transactions_sync_request_options'
require 'plaid_compatible/money_kit_plaid_compatible/models/transactions_sync_response'
require 'plaid_compatible/money_kit_plaid_compatible/models/validation_error'
require 'plaid_compatible/money_kit_plaid_compatible/models/webhook_environment_values'

# APIs
require 'plaid_compatible/money_kit_plaid_compatible/api/plaid_api'

module MoneyKit::PlaidCompatible
  class << self
    # Customize default settings for the SDK using block.
    #   MoneyKit::PlaidCompatible.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
