name: Release

# on:
#   release:
#     types: [released]
on:
  push:
    tags:
      - "v*"

jobs:
  publish_to_rubygems:
    name: Publish to Ruby Gems
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Get tags for automatic versioning

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2.2"
          bundler-cache: true

      # - name: Run tests
      #   run: bundle exec rspec

      - name: Build gem
        run: |
          gem build moneykit.gemspec

      - name: Setup Ruby Gems access
        run: |
          mkdir -p ~/.gem
          echo ":rubygems_api_key: ${{ secrets.RUBYGEMS_API_KEY }}" > ~/.gem/credentials
          chmod 0600 ~/.gem/credentials

      - name: Publish gem
        run: |
          gem push moneykit-*.gem
